worker: fxstreet

http:
  timeout: 15.0
  max_retries: 3
  retry_backoff_base: 2.0
  rate_limit_delay: 1.0
  proxy_url: null

s3:
  bucket_name: fxstreet
  use_ssl: false
  region: us-east-1

raw_output_name_template: fxstreet/events/{start_date}_{end_date}.json
